name: Daily Data Fetch

on:
  schedule:
    - cron: '0 23 * * *'  # Runs daily at 23:00 UTC (midnight GMT)
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Adjust to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run fetch_data.py
      env:
        SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
      run: python fetch_data.py

    - name: Commit database changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add news.db
        git commit -m "Update database with new data" || echo "No changes to commit"
        git push
      continue-on-error: true